### ISSUE TITLE
formResponse.actionAfterSuccess is always null

### ISSUE THREAD

**Issue by JeanM38** [TYPO3-Headless/nuxt-typo3#324]
Hello !

I created a form in TYPO3 Backend with the Forms module, and assign it to a specifig page, form is well rendered in my front-end application, but I don't understand why **formResponse.actionAfterSuccess** in the **T3CeFormFormframework.vue** component is always null after the form submission, I created different finishers for this form so I would like to retrieve them. This is a classic form configuration : 

```yaml

renderingOptions:
  submitButtonLabel: Submit
identifier: contact
label: Contact
type: Form
prototypeName: standard
finishers:
  -
    options:
      message: GG
      contentElementUid: ''
    identifier: Confirmation
renderables:
  -
    renderingOptions:
      previousButtonLabel: 'Previous step'
      nextButtonLabel: 'Next step'
    identifier: page-1
    label: 'Contact Form'
    type: Page
    renderables:
      -
        defaultValue: MIONNET
        identifier: name
        label: Name
        type: Text
        properties:
          fluidAdditionalAttributes:
            placeholder: Name
            required: required
        validators:
          -
            identifier: NotEmpty
      -
        defaultValue: Sujet
        identifier: subject
        label: Subject
        type: Text
        properties:
          fluidAdditionalAttributes:
            placeholder: Subject
            required: required
        validators:
          -
            identifier: NotEmpty
      -
        defaultValue: jmionnet@emagineurs.com
        identifier: email
        label: Email
        type: Text
        properties:
          fluidAdditionalAttributes:
            placeholder: 'Email address'
            required: required
        validators:
          -
            identifier: NotEmpty
          -
            identifier: EmailAddress
      -
        defaultValue: Message
        identifier: message
        label: Message
        type: Textarea
        properties:
          fluidAdditionalAttributes:
            placeholder: ''
            required: required
        validators:
          -
            identifier: NotEmpty

```

Maybe I forgot something ? Thanks for the answer.

## Versions
TYPO3 [12.4.4] . TYPO3 Headless [4.2.2] . nuxt [2.17.2] . nuxt-typo3 [1.3.3]
